### ISSUE TITLE
Error after clicking show time of any movie in website

### ISSUE THREAD

**Issue by yashsalunke639** [gosaliajainam/online-movie-booking#1]
![Screenshot (3)](https://user-images.githubusercontent.com/87906151/187729093-91952f1d-ced2-489c-b753-9c3a95a7bac5.png)

**Comment by gosaliajainam** [comment]
The '&&' operator is not placed on line 72 in the seatbooking.php file. Hence this error occurs.

$result = mysqli_query($conn,"SELECT * FROM customers WHERE show_time = '".$time."' && movie = '".$movie."' && payment_date = '".$date."'");

Update this query across line 72, so this error will be solved.

**Comment by gosaliajainam** [comment]
> The '&&' operator is not placed on line 72 in the seatbooking.php file. Hence this error occurs.
> 
> $result = mysqli_query($conn,"SELECT * FROM customers WHERE show_time = '".$time."' && movie = '".$movie."' && payment_date = '".$date."'");
> 
> Update this query across line 72, so this error will be solved.
